### ISSUE TITLE
Unlock Pseudonyms after 15 minutes

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-rethinkdb-database#1]
The table "PseudonymList" contains all used pseudonyms and only locked pseudonyms. Locked Pseudonyms indicate that a user recently got a suggestion and the pseudonym is reserved for a certain duration.

Currently the PseudonymList can only get bigger. Every pseudonym has a time stamp which indicates the time when the user locked the pseudonym.
It is important that a pseudonym doesn't get removed from the PseudonymList to prevent duplicate pseudonyms. Remove the lock time for that (or something else).

**Comment by 5cript** [comment]
Expired locked pseudonyms are now removed after some (default = 15) minutes.
