### ISSUE TITLE
Corrector lock next should not lock a already assigned solution

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-rethinkdb-database#3]
If you lock a solution it should not overwrite locks of other tutors. The locking function (`corrector.js` in `lockNextSolutionForTutor`) should also prevent a tutor from locking too many solutions.

**Comment by 5cript** [comment]
It does seem to be implemented, maybe you want to review your own code to remember what you meant.

Locking to many solutions: Not yet implemented though!

**Comment by 5cript** [comment]
The amount of lockable solutions (by tutor) is now restricted to a maximum (default = 10).
