### ISSUE TITLE
Remove internals and solution from Exercise.*

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-rethinkdb-database#4]
All Exercise.\* queries should remove the internals part and the solution in every task. Otherwise a student-user could see the solution in the API call.

**Comment by LittleHelicase** [comment]
I just added the `solutionTest` field to each task. This should also be removed from the tasks in the exercise queries. (This is most probably the last one ;) ).

**Comment by 5cript** [comment]
the solution and solutionTest field are now removed from the task array of exercise queries.
This is also true for the memory database.
Also fixed and added to the two tests that were there to test this.
