### ISSUE TITLE
Solution Locking shall save its time and date for display

### ISSUE THREAD

**Issue by 5cript** [Welfenlab/tutor-rethinkdb-database#5]
Title says it all.
If we implement a list to display all unfinished solutions, the tutor should be able to have a sense of
which is which.

**Comment by leMaik** [comment]
At the moment, there is no such list. The tutor can only correct the "next" solution (which may not even be one that he hasn't seen before). See Welfenlab/tutor-corrector#12.

**Comment by 5cript** [comment]
Done in foresight and finished.
